{
 "title": "InfluxCloud Usage Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_in_cost", "label": "Data In $/MB", "query": "0.002" },
   { "name": "query_cost", "label": "Query Cost $/100 queries", "query": "0.01" },
   { "name": "storage_cost", "label": "Storage $/GB-hour", "query": "0.002" },
   { "name": "data_out_cost", "label": "Data out $/GB", "query": "0.09" }
  ]
 },
 "panels": [
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Data In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n   |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and (r.endpoint == \"/api/v2/write\" or r.endpoint == \"/write\")\n      and r._field == \"req_bytes\"\n    )\n    |> group()\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()"
    }
   ]
  },
  {
   "title": "Total Data Out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and r._field == \"resp_bytes\"\n      and (r.endpoint == \"/api/v2/query\" or r.endpoint == \"/query\")\n    )    \n    |> filter(fn: (r) => r.status == \"200\")\n    |> group()\n    |> aggregateWindow(every: 1h, fn: sum)\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()"
    }
   ]
  },
  {
   "title": "Query Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> filter(fn: (r) =>\n      r._measurement == \"query_count\"\n    )\n    |> group(columns: [\"_time\"])\n    |> sum()\n    |> group()\n    |> rename(columns: {_value: \"query_count\"})\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum(column: \"query_count\")"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "GB-hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> filter(fn: (r) => r._measurement == \"storage_usage_bucket_bytes\" and r._field == \"gauge\")\n    |> range(start: 0)\n    |> aggregateWindow(every: 1h, fn: mean)\n    |> fill(column: \"_value\", value: 0.0)\n    |> group()\n    |> sum()\n    |> map(fn: (r) =>\n      ({r with\n        _value: math.round(x: float(v: r._value) / 10000000.0) / 100.0\n      })\n    )"
    }
   ]
  },
  {
   "title": "Total Cardinality",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb\"\nimport \"influxdata/influxdb/schema\"\n\nbuckets()\n  |> map(fn: (r) => {\n    cards = influxdb.cardinality(start: 1970-01-01T00:00:00Z, bucket: r.name)\n      |> findRecord(idx: 0, fn: (key) => (true))\n    return {r with cardinality: cards._value}\n  })\n  |> sum(column: \"cardinality\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Cardinality Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\nimport \"csv\"\nlimits = usage.limits()\ncsvData = \"#datatype,string,long,string\n#group,false,false,false\n#default,,,\n,result,table,column\n,,0,*\n\"\ncsv.from(csv: csvData)\n  |> map(fn: (r) => ({\n    cardinality: limits.rate.cardinality\n  }))"
    }
   ]
  },
  {
   "title": "Data In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\" \nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n   |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and (r.endpoint == \"/api/v2/write\" or r.endpoint == \"/write\")\n      and r._field == \"req_bytes\"\n    )\n    |> group()\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"], desc: true)\n    "
    }
   ]
  },
  {
   "title": "Data Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\nimport \"math\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop\n)\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and r._field == \"resp_bytes\"\n      and (r.endpoint == \"/api/v2/query\" or r.endpoint == \"/query\")\n    )\n    |> filter(fn: (r) => r.status == \"200\")\n    |> keep(columns: [\"_value\", \"status\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Query Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart, \n    stop: v.timeRangeStop,\n)\n   |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n      r._measurement == \"query_count\"\n    )\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n |> sort(columns: [\"_time\"], desc: false)   \n\n\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> set(key: \"_field\", value: \"queries\")\n  "
    }
   ]
  },
  {
   "title": "Storage (by Bucket)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\n\n//Data returned from usage.from() uses the ID value for the buckets. This function will remap the data to use the name of the bucket\nb = buckets()\nbucketNameForID = (id) => {\n    row = b \n        |> filter(fn: (r) => r.id == id) \n        |> findRecord(fn: (key) => true, idx: 0)\n    return row.name\n}\n\nbucket_ids = b \n    |> findColumn(fn: (key) => true, column: \"id\")\n\ndata_buckets = usage.from(start: v.timeRangeStart,\n    stop: v.timeRangeStop) \n    |> filter(fn: (r) => r._measurement == \"storage_usage_bucket_bytes\")\n    |> map(fn: (r) => ({ r with bucket_name: if contains(value: r[\"bucket_id\"], set: bucket_ids) then bucketNameForID(id: r[\"bucket_id\"]) else \"unknown bucket\"}))\n    |> keep(columns: [\"_time\", \"_value\", \"bucket_id\", \"bucket_name\"])\n    |> group(columns: [\"bucket_name\"])\n\ndata_all = data_buckets\n    |> group(columns: [\"_time\"])\n    |> sum()\n    |> group()\n    |> set(key: \"bucket_name\", value: \"all buckets\")\n\nunion(tables: [data_buckets, data_all])\n    |> group(columns: [\"bucket_name\"])"
    }
   ]
  },
  { "title": "Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Estimated Total Cost",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": {
    "content": "# Costs\n\nThis section provides an estimate of billing costs based on usage and the pricing entered in the dashboard's variables.\n\nUp to date pricing for InfluxCloud can be found at https://www.influxdata.com/influxdb-pricing/"
   },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> range(start: 2021-03-01T00:00:00.000Z)\n  |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and r._field == \"resp_bytes\"\n      and (r.endpoint == \"/api/v2/query\" or r.endpoint == \"/query\")\n    )\n    |> group()\n    |> aggregateWindow(every: 1h, fn: sum)\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n        |> map(fn: (r) =>\n    ({r with\n      _value: math.round(x: float(v: r._value) / 10000000.0) / 100.0 * ${data_out_cost}\n    }))\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()\n"
    },
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n   |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and (r.endpoint == \"/api/v2/write\" or r.endpoint == \"/write\")\n      and r._field == \"req_bytes\"\n    )\n    |> group()\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()\n    |> map(fn: (r) => ({r with _value: math.round(x: float(v: r._value) / 10000.0) / 100.0 * ${data_in_cost} })) \n"
    },
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n//   |> range(start: 2021-03-01T00:00:00.000Z)\n  |> filter(fn: (r) =>\n      r._measurement == \"query_count\"\n    )\n    |> group(columns: [\"_time\"])\n    |> sum()\n    |> group()\n    |> rename(columns: {_value: \"query_count\"})\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum(column: \"query_count\")\n    |> map(fn: (r) => ({\n       _value: (float(v:r._value) / 100.00) * ${query_cost}\n    }))"
    },
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> filter(fn: (r) => r._measurement == \"storage_usage_bucket_bytes\" and r._field == \"gauge\")\n    |> range(start: 2021-03-01T00:00:00.000Z)\n    |> aggregateWindow(every: 1h, fn: mean)\n    |> fill(column: \"_value\", value: 0.0)\n    |> group()\n    |> sum()\n    |> map(fn: (r) =>\n      ({r with\n        _value: (math.round(x: float(v: r._value) / 10000000.0) / 100.0) * ${storage_cost}\n      })\n    )\n\n"
    }
   ]
  },
  {
   "title": "Estimated Total Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n   |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and (r.endpoint == \"/api/v2/write\" or r.endpoint == \"/write\")\n      and r._field == \"req_bytes\"\n    )\n    |> filter(fn: (r) => r.status == \"200\")\n    |> group()\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()\n    |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000000000.0 / 100.0 * ${data_in_cost} })) \n"
    },
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n   |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and (r.endpoint == \"/api/v2/write\" or r.endpoint == \"/write\")\n      and r._field == \"req_bytes\"\n    )\n    |> filter(fn: (r) => r.status == \"204\")\n    |> group()\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()\n    |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000000.0 / 100.0 * ${data_in_cost} })) "
    },
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from( \n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> filter(fn: (r) =>\n      r._measurement == \"query_count\"\n    )\n    |> group(columns: [\"_time\"])\n    |> sum()\n    |> group()\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()\n    |> map(fn: (r) => ({\n       _value: (float(v:r._value) / 100.00) * ${query_cost}\n    }))"
    },
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> filter(fn: (r) => r._measurement == \"storage_usage_bucket_bytes\" and r._field == \"gauge\")\n  |> range(start: v.timeRangeStart)\n    |> aggregateWindow(every: 1h, fn: mean)\n    |> fill(column: \"_value\", value: 0.0)\n    |> group()\n    |> sum()\n    |> map(fn: (r) =>\n      ({r with\n        _value: ((float(v: r._value) / 10000000.0) / 100.0) * ${storage_cost}\n      })\n    )\n"
    }
   ]
  },
  {
   "title": "Estimated Data In Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n   |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and (r.endpoint == \"/api/v2/write\" or r.endpoint == \"/write\")\n      and r._field == \"req_bytes\"\n    )\n    |> filter(fn: (r) => r.status == \"204\")\n    |> group()\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()\n    |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000000.0 / 100.0 * ${data_in_cost} })) "
    }
   ]
  },
  {
   "title": "Estimated Data Out Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) =>\n        r._measurement == \"http_request\"\n        and r._field == \"resp_bytes\"\n        and (r.endpoint == \"/api/v2/query\" or r.endpoint == \"/query\")\n        )\n    |> filter(fn: (r) => r.status == \"200\")\n    |> group()\n    |> aggregateWindow(every: 1h, fn: sum)\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> filter(fn: (r) => exists r._value)\n    |> group()    \n    |> sum()\n    |> map(fn: (r) =>\n        ({ \n            // Convert to GBs and then to dollars before applying pricing\n            _value: (float(v: r._value) / 1000000000.0) / 100.0 * ${data_out_cost}\n        }))\n\n\n"
    }
   ]
  },
  {
   "title": "Estimated Query Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from( \n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> filter(fn: (r) =>\n      r._measurement == \"query_count\"\n    )\n    |> group(columns: [\"_time\"])\n    |> sum()\n    |> group()\n    |> sort(columns: [\"_time\"])\n    |> group()\n    |> sum()\n    |> map(fn: (r) => ({\n        _value: (float(v:r._value) / 100.00) * ${query_cost}\n    }))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> filter(fn: (r) => r._measurement == \"storage_usage_bucket_bytes\" and r._field == \"gauge\")\n  |> range(start: v.timeRangeStart)\n    |> aggregateWindow(every: 1h, fn: mean)\n    |> fill(column: \"_value\", value: 0.0)\n    |> group()\n    |> sum()\n    |> map(fn: (r) =>\n      ({r with\n        _value: ((float(v: r._value) / 10000000.0) / 100.0) * ${storage_cost}\n      })\n    )\n\n"
    }
   ]
  },
  {
   "title": "Data In Estimated Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\" \nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n   |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and (r.endpoint == \"/api/v2/write\" or r.endpoint == \"/write\")\n      and r._field == \"req_bytes\"\n    )\n    |> group()\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> fill(column: \"_value\", value: 0)\n    |> sort(columns: [\"_time\"], desc: true)\n    |> map(fn: (r) => ({r with _value: (float(v: r._value) / 1000000.0) * ${data_in_cost}}))\n    \n    "
    }
   ]
  },
  {
   "title": "Data Out Estimated Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\nimport \"math\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop\n)\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n      r._measurement == \"http_request\"\n      and r._field == \"resp_bytes\"\n      and (r.endpoint == \"/api/v2/query\" or r.endpoint == \"/query\")\n    )\n    |> filter(fn: (r) => r.status == \"200\")\n    |> keep(columns: [\"_value\", \"status\", \"_time\"])\n    |> map(fn: (r) => ({r with _value: (float(v: r._value) / 1000000000.0) * ${data_out_cost}}))"
    }
   ]
  },
  {
   "title": "Estimated Query Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "import \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart, \n    stop: v.timeRangeStop,\n)\n   |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n      r._measurement == \"query_count\"\n    )\n    |> keep(columns: [\"_value\", \"_field\", \"_time\"])\n    |> sort(columns: [\"_time\"], desc: false)   \n\n\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> map(fn: (r) => ({r with _value: (float(v: r._value) / 100.0) * ${query_cost}}))"
    }
   ]
  },
  {
   "title": "Storage (by Bucket)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\n\n//Data returned from usage.from() uses the ID value for the buckets. This function will remap the data to use the name of the bucket\nb = buckets()\nbucketNameForID = (id) => {\n    row = b \n        |> filter(fn: (r) => r.id == id) \n        |> findRecord(fn: (key) => true, idx: 0)\n    return row.name\n}\n\nbucket_ids = b \n    |> findColumn(fn: (key) => true, column: \"id\")\n\ndata_buckets = usage.from(start: v.timeRangeStart,\n    stop: v.timeRangeStop) \n    |> filter(fn: (r) => r._measurement == \"storage_usage_bucket_bytes\")\n    |> map(fn: (r) => ({ r with bucket_name: if contains(value: r[\"bucket_id\"], set: bucket_ids) then bucketNameForID(id: r[\"bucket_id\"]) else \"unknown bucket\"}))\n    |> keep(columns: [\"_time\", \"_value\", \"bucket_id\", \"bucket_name\"])\n    |> group(columns: [\"bucket_name\"])\n\ndata_all = data_buckets\n    |> group(columns: [\"_time\"])\n    |> sum()\n    |> group()\n    |> set(key: \"bucket_name\", value: \"all buckets\")\n\nunion(tables: [data_buckets, data_all])\n    |> group(columns: [\"bucket_name\"])\n    |> map(fn: (r) => ({r with _value: (float(v: r._value) / 1000000000.0)* ${storage_cost}}))"
    }
   ]
  },
  { "title": "Rate Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Write Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\nimport \"csv\"\nlimits = usage.limits()\ncsvData = \"#datatype,string,long,string\n#group,false,false,false\n#default,,,\n,result,table,column\n,,0,*\n\"\ncsv.from(csv: csvData)\n  |> map(fn: (r) => ({\n    write: limits.rate.writeKBs\n  }))"
    }
   ]
  },
  {
   "title": "Read Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\nimport \"csv\"\nlimits = usage.limits()\ncsvData = \"#datatype,string,long,string\n#group,false,false,false\n#default,,,\n,result,table,column\n,,0,*\n\"\ncsv.from(csv: csvData)\n  |> map(fn: (r) => ({\n    read: limits.rate.readKBs\n  }))"
    }
   ]
  },
  {
   "title": "Cardinality Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental/usage\"\nimport \"csv\"\nlimits = usage.limits()\ncsvData = \"#datatype,string,long,string\n#group,false,false,false\n#default,,,\n,result,table,column\n,,0,*\n\"\ncsv.from(csv: csvData)\n  |> map(fn: (r) => ({\n    cardinality: limits.rate.cardinality\n  }))"
    }
   ]
  },
  {
   "title": "Write Limiting Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\n\ndata_0 = array.from(rows:[{_value: 0}])\ndata = usage.from(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"events\" and r._field == \"event_type_limited_write\")\n  |> sum(column: \"_value\")\nunion(tables: [data_0, data])"
    }
   ]
  },
  {
   "title": "Read Limiting Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\n\ndata_0 = array.from(rows:[{_value: 0}])\ndata = usage.from(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"events\" and r._field == \"event_type_limited_query\")\n  |> sum(column: \"_value\")\nunion(tables: [data_0, data])"
    }
   ]
  },
  {
   "title": "Cardinality Limiting Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\n\ndata_0 = array.from(rows:[{_value: 0}])\ndata = usage.from(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"events\" and r._field == \"event_type_limited_cardinality\")\n  |> sum(column: \"_value\")\nunion(tables: [data_0, data])"
    }
   ]
  },
  {
   "title": "Rate Limiting Events",
   "type": "timeseries",
   "description": "If you exceed your plan's limits, the event will be logged to help you track when the events occur. For more information on your rate limits, check out our documentation. \n\nhttps://docs.influxdata.com/influxdb/cloud/account-management/data-usage/#exceeded-rate-limits",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "query": "import \"csv\"\nimport \"math\"\nimport \"date\"\nimport \"strings\"\nimport \"experimental/json\"\nimport \"experimental/usage\"\n\nusage.from(\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop,\n)\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) =>\n      r._measurement == \"events\"\n    )\n  |> sort(columns: [\"_time\"], desc: false)  \n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  }
 ]
}